name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
  minimum_version_check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build for iOS 12
        run: xcodebuild build -scheme UnleashProxyClientSwift -destination 'generic/platform=iOS' IPHONEOS_DEPLOYMENT_TARGET=12.0
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --sanitize=thread
  thread_safety_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run thread safety tests
        run: UNLEASH_THREAD_SAFETY_TEST=1 swift test --filter UnleashThreadSafetyTest
